/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coursework;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rikin
 */
public class FinishedRace extends javax.swing.JFrame {
        String username;
        String track;
        String time;
    public FinishedRace() throws FileNotFoundException, IOException {
        initComponents();
        setBounds(400, 200, 600, 335);
        
        BufferedReader br1 = new BufferedReader(new FileReader("Username.txt"));
        try {
            StringBuilder sb1 = new StringBuilder();
            String line = br1.readLine();
            while (line != null) {
                sb1.append(line);
                sb1.append(System.lineSeparator());
                line = br1.readLine();
            }
            username = sb1.toString();
        } finally {
            br1.close();
        }
        
        BufferedReader br2 = new BufferedReader(new FileReader("Track.txt"));
        try {
            StringBuilder sb2 = new StringBuilder();
            String line = br2.readLine();
            while (line != null) {
                sb2.append(line);
                sb2.append(System.lineSeparator());
                line = br2.readLine();
            }
            track = sb2.toString();
        } finally {
            br2.close();
        }
        
        BufferedReader br = new BufferedReader(new FileReader("LapTime.txt"));
        try {
            StringBuilder sb = new StringBuilder();
            String line = br.readLine();
            while (line != null) {
                sb.append(line);
                sb.append(System.lineSeparator());
                line = br.readLine();
            }
            time = sb.toString();
            LapTime.setText(time);
        } finally {
            br.close();
        }
        //Reads from LapTime text file and stores contents in time, then displays it on JLabel
        
        
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LapTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        LapTime.setFont(new java.awt.Font("Terminator Two", 2, 20)); // NOI18N
        LapTime.setForeground(new java.awt.Color(234, 255, 255));
        getContentPane().add(LapTime);
        LapTime.setBounds(230, 170, 170, 40);

        jLabel1.setFont(new java.awt.Font("Magneto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONGRATULATIONS!!!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 540, 50);

        jLabel5.setFont(new java.awt.Font("Terminator Two", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(234, 255, 255));
        jLabel5.setText("You have successfully completed");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 110, 460, 40);

        jLabel6.setFont(new java.awt.Font("Terminator Two", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(234, 255, 255));
        jLabel6.setText("the track with a time of: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 140, 350, 40);

        jButton1.setBackground(new java.awt.Color(0, 193, 255));
        jButton1.setFont(new java.awt.Font("Terminator Two", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Submit Score");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 270, 150, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/Finish Background.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 335);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String csvFilename = "LeaderBoard.csv";
        try {
            FileWriter writer = new FileWriter(csvFilename, true);
            writer.append('\n');
            writer.append(username + ',' + track + ',' + time);
            writer.close();
        } catch (Exception e) {
        }
        //Appends leader board file to add new row of user data
        
        new StartMenuUI().setVisible(true);
        this.dispose();
        //Opens start menu screen and closes congratulations pop up screen
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinishedRace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinishedRace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinishedRace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinishedRace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FinishedRace().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(FinishedRace.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LapTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
