/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coursework;

import javax.swing.JFrame;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.FileNotFoundException;

/**
 *
 * @author Rikin
 */
public class TrackMenuUI extends javax.swing.JFrame {

    /**
     * Creates new form TrackMenuUI
     */
    public TrackMenuUI() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        //Makes the JFrame full screen
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel10.setFont(new java.awt.Font("Terminator Two", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 242, 86));
        jLabel10.setText("Track 6 (Hard)");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(810, 540, 280, 60);

        jLabel9.setFont(new java.awt.Font("Terminator Two", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 242, 86));
        jLabel9.setText("Track 5 (Hard)");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(310, 540, 250, 60);

        jLabel8.setFont(new java.awt.Font("Terminator Two", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 242, 86));
        jLabel8.setText("Track 4 (Medium)");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(810, 340, 280, 60);

        jLabel7.setFont(new java.awt.Font("Terminator Two", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 242, 86));
        jLabel7.setText("Track 3 (Medium)");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(300, 340, 280, 60);

        jLabel5.setFont(new java.awt.Font("Terminator Two", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 242, 86));
        jLabel5.setText("Track 2 (Easy)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(820, 150, 250, 60);

        jLabel6.setFont(new java.awt.Font("Terminator Two", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 242, 86));
        jLabel6.setText("Track 1 (Easy)");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 150, 250, 60);

        jLabel1.setFont(new java.awt.Font("Magneto", 1, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(100, 200, 250));
        jLabel1.setText("Select Track");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 10, 720, 150);

        jButton4.setBackground(new java.awt.Color(255, 123, 35));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/Track 6 Preview.png"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(820, 600, 240, 140);

        jButton5.setBackground(new java.awt.Color(255, 123, 35));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/Track 1 Preview.png"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(310, 210, 240, 130);

        jButton6.setBackground(new java.awt.Color(255, 123, 35));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/Track 2 Preview.png"))); // NOI18N
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(820, 210, 240, 130);

        jButton7.setBackground(new java.awt.Color(255, 123, 35));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/Track 3 Preview.png"))); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(310, 400, 240, 130);

        jButton8.setBackground(new java.awt.Color(255, 123, 35));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/Track 4 Preview.png"))); // NOI18N
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(820, 390, 240, 140);

        jButton9.setBackground(new java.awt.Color(255, 123, 35));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/Track 5 Preview.png"))); // NOI18N
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(310, 600, 240, 140);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/Car & Track Menu.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1370, 770);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int userTrack = 1;
        //Stores the track number as an integer in userTrack
        
        PrintWriter writer = null;
        try {
            writer = new PrintWriter("Track.txt", "UTF-8");
            writer.println(userTrack);
            writer.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CarMenuUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(CarMenuUI.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            writer.close();
        }
        //Writes the number of the selected track into a text file
        
        new TrackI().setVisible(true);
        this.dispose();
        //Opens the corresponding track gameplay screen and closes the track menu screen
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int userTrack = 2;
        PrintWriter writer = null;
        try {
            writer = new PrintWriter("Track.txt", "UTF-8");
            writer.println(userTrack);
            writer.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CarMenuUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(CarMenuUI.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            writer.close();
        }
        new TrackII().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int userTrack = 3;
        PrintWriter writer = null;
        try {
            writer = new PrintWriter("Track.txt", "UTF-8");
            writer.println(userTrack);
            writer.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CarMenuUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(CarMenuUI.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            writer.close();
        }
        new TrackIII().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int userTrack = 4;
        PrintWriter writer = null;
        try {
            writer = new PrintWriter("Track.txt", "UTF-8");
            writer.println(userTrack);
            writer.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CarMenuUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(CarMenuUI.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            writer.close();
        }
        new TrackIV().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int userTrack = 5;
        PrintWriter writer = null;
        try {
            writer = new PrintWriter("Track.txt", "UTF-8");
            writer.println(userTrack);
            writer.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CarMenuUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(CarMenuUI.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            writer.close();
        }
        new TrackV().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int userTrack = 6;
        PrintWriter writer = null;
        try {
            writer = new PrintWriter("Track.txt", "UTF-8");
            writer.println(userTrack);
            writer.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CarMenuUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(CarMenuUI.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            writer.close();
        }
        new TrackVI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrackMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrackMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrackMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrackMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrackMenuUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
